apiVersion: batch/v1
kind: Job
metadata:
  name: manifests-test-job
  namespace: %TEST_NAMESPACE%
  labels:
    app:  manifests-test-job
    test: osd-e2e-test
spec:
  backoffLimit: 2
  completions: 1
  template:
    metadata:
      name: manifests-test-pod
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - $HOME/peak/installandtest.sh
        env:
        - name: PATH
          value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        - name: TEST_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ARTIFACT_DIR
          value: ${ARTIFACT_DIR}
        image: %MANIFESTS_FULL_IMG_URL%
        name: manifests-test
        resources: {}
        volumeMounts:
        - mountPath: %ARTIFACT_DIR%
          name: artifacts
      volumes:
      - name: artifacts
        persistentVolumeClaim:
          claimName: ods-ci
      restartPolicy: Never
      serviceAccountName: %MANIFESTS_NAME%-sa
