IMAGE_REGISTRY=quay.io
REGISTRY_NAMESPACE=jooholee
IMAGE_TAG=latest

TEST_HARNESS_NAME=operator-test-harness
MANIFESTS_TEST=manifests-test
TEST_NAMESPACE=${TEST_HARNESS_NAME}
IMAGE=${TEST_HARNESS_NAME}


# Do Not Change
TEST_HARNESS_FULL_IMAGE_NAME=${IMAGE_REGISTRY}/${REGISTRY_NAMESPACE}/${TEST_HARNESS_NAME}:${IMAGE_TAG}





