IMAGE_REGISTRY=quay.io
REGISTRY_NAMESPACE=jooholee
IMAGE_TAG=latest

TEST_HARNESS_NAME=nfs-operator-test-harness
MANIFESTS_TEST=nfs-manifests-test
TEST_NAMESPACE=${TEST_HARNESS_NAME}



# Do Not Change
TEST_HARNESS_FULL_IMAGE_NAME=${IMAGE_REGISTRY}/${REGISTRY_NAMESPACE}/${TEST_HARNESS_NAME}:${IMAGE_TAG}